### ISSUE TITLE
Copy all headers, not only selected ones

### ISSUE THREAD

**Issue by duckdalbe** [jkraemer/mail-gpg#24]
[gpg.rb:103ff](https://github.com/jkraemer/mail-gpg/blob/master/lib/mail/gpg.rb#L103) defines and uses a list of "standard" and "more" headers that are to be copied from the cleartext email to the new wrapper email. That list is not sufficient, there's a lot more headers in legitimate use. Personally I'd like to use the List-*-headers.

Is there any reason to exclude them from the list of allowed headers? They're even standardized in own RFCs  (e.g. List-Id, from [RFC 2919](http://www.faqs.org/rfcs/rfc2919.html)).

[Edit: I see List-Id has been added to the list. Still missing are List-Post, List-Help and others.]

Beyond that I'm wondering what the motivation for this list is. Why not just copy all headers except those that need to change? If I want to include a header of my choice (standardized or not) I should be able to do so, no?

**Comment by duckdalbe** [comment]
Thanks for merging!

I'd still be interested in your motivation to filter the headers, though: Is it to keep people from passing on too much potentially sensitive information?

Thanks again!

**Comment by jkraemer** [comment]
On 02/20, Fup Duck wrote:
> Thanks for merging!

Well, sorry it happened so late ;)

> I'd still be interested in your motivation to filter the headers, though: Is
> it to keep people from passing on too much potentially sensitive information?

Yes, something in the line of this. But I agree that we might be doing too much
here and this could be an optional feature.

Cheers,
Jens


-- 
Jens Krämer
https://jkraemer.net/

**Comment by ryantate** [comment]
This is a great gem, thank you for writing and maintaining it!

I do agree that the selective copying of headers is undesirable. It seems orthogonal to what this gem does -- encrypt and decrypt mail bodies/attachments. The ideal/expected solution would be to simply encrypt or decrypt those bits and leave the rest of the mail alone.

In my case I was missing Return-Path and Received headers after decrypt. 

But I don't think the right approach is to add these to some whitelist of headers. Filtering headers seems outside the scope of this module. I would go so far as to say it is unexpected behavior.

If there are some headers the break due to encryption or decryption (like DKIM-Signature) it makes sense to have an optional blacklist for those, perhaps, and filter them out. But it hardly makes sense to delete unknown email headers by default (even if they don't have an X-), particularly given you can't be expected to have too much knowledge of what headers are in the wild.

Side note, for myself, for now, I fixed this by doing the following:

```
mail = Mail.new mail_text
if mail.encrypted?
  decrypted_mail = mail.decrypt
  decrypted_mail.header = mail.header.to_s
```

**Comment by duckdalbe** [comment]
Is there a reason why `decrypt_pgp_mime()` doesn't use `STANDARD_HEADERS` but a slightly shorter list (stripped by `return_path` and `message_id`) at [line 139](https://github.com/jkraemer/mail-gpg/blob/master/lib/mail/gpg.rb#L139)?

**Comment by jkraemer** [comment]
please check out 0.3.0, this should fix this issue.
